#HWIFI Main module
CONFIG_HWIFI=m

#HWIFI Features
CONFIG_HWIFI_HE_SUPPORT=n
CONFIG_HWIFI_SW_AMSDU=n
CONFIG_HWIFI_MEM_SHRINK=y

#HWIFI DBG
CONFIG_HWIFI_DBG=n
CONFIG_HWIFI_DBG_ISR=n

#HWIFI HIF modules
CONFIG_HWIFI_HIF_PCI=m
CONFIG_HWIFI_HIF_WED=n
CONFIG_HWIFI_HIF_NPU=n
CONFIG_HWIFI_RRO=m

#HWIFI Interface modules
CONFIG_HWIFI_IF_CONNAC=m
CONFIG_HWIFI_IF_MAC80211=n

#HWIFI Chip modules
CONFIG_HWIFI_CHIP_MT7915=m
CONFIG_HWIFI_CHIP_MT7916=m
CONFIG_HWIFI_CHIP_BELLWETHER=m
CONFIG_HWIFI_CHIP_MT7990=m
CONFIG_HWIFI_CHIP_MT7991=m
CONFIG_HWIFI_CHIP_MT7992=m
CONFIG_HWIFI_CHIP_MT799A=m
CONFIG_HWIFI_CHIP_MT7993=m
CONFIG_HWIFI_CHIP_MT799B=m
CONFIG_HWIFI_CHIP_MT7915_DBG=m
CONFIG_HWIFI_CHIP_MT7990_DBG=m
CONFIG_HWIFI_CHIP_MT7992_DBG=m
CONFIG_HWIFI_CHIP_MT7993_DBG=m

#HWIFI Others
#Eagle only
CONFIG_HWIFI_USE_PCIE0_TXRING21=n

#HWIFI SW Path Rx process
CONFIG_HWIFI_RX_PROCESS_WORKQUEUE=n
