name: Build ImmortalWrt

on:
  workflow_dispatch: # 允许手动在网页触发

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    
    steps:
      - name: Checkout My Repository Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史，方便某些脚本获取版本号（可选）

      - name: Initialize Build Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          # 安装 OpenWrt/ImmortalWrt 构建所需依赖
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          
          sudo timedatectl set-timezone "Asia/Shanghai"
      

      - name: Update and Install Feeds
        run: |
          # 当前目录已经是源码根目录
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Configuration (mt7987_mt7992)
        run: |
          
          cp -f defconfig/mt7987_mt7992.config .config
          echo "✅ Successfully loaded defconfig/mt7987_mt7992.config"
          
          # 执行 make defconfig 以确保配置完整并处理依赖
          make defconfig 
          
          # 👇 打印 .config 文件内容到日志
          echo "📄 Content of .config:"
          cat .config

      - name: Compile Firmware
        run: |
          # 开始编译
          # -j$(nproc) 使用所有可用 CPU 核心
          # V=s 输出详细日志以便排查错误
          make -j$(nproc) V=s
      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          files: |
            bin/targets/mediatek/filogic/*
          draft: true


